server:
  port: 5000
# Datasource
spring:
  datasource:
    driver-class-name: org.hsqldb.jdbc.JDBCDriver
    url: jdbc:hsqldb:mem:restapi;DB_CLOSE_DELAY=-1
    username: sa
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
# Swagger path
springdoc:
  api-docs:
    path: /api-docs
# Swagger version
my:
  api:
    version: @project.version@
    title: Online store project backend API
    description: This is a documentation of the API Online store project backend
# Logging
logging:
  level:
    root: INFO