server:
  port: 5000
# Datasource
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  sql:
    init:
      schema-locations: classpath*:database/schema.sql
      mode: always
  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: update
    open-in-view: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  #Spring mail
  mail:
    host: smtp.gmail.com
    default-encoding: UTF-8
    port: 587
    username: ${APP_EMAIL}
    password: ${APP_EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
# Swagger path
springdoc:
  api-docs:
    path: /api-docs
# Swagger version
my:
  api:
    version: @project.version@
    title: Online store project backend API
    description: This is a documentation of the API Online store project backend
# Logging
logging:
  level:
    root: INFO
app:
  front:
    url: https://olgaoo7.github.io/clothing-store-app
  product:
    price-delta-for-similar-products: 300.0
  security:
    admin-password: ${ADMIN_PASSWORD}
    user-password: ${USER_PASSWORD}
  subscription:
    time:
      cron: 0 0 9 * * *
      zone: Europe/Kiev
  email-sales-manager: salesmanager622@gmail.com